export { Initial }  from "./initial" 
export { Menu }  from "./menu" 
export { Profissional }  from "./profissional"
export { Paciente } from "./paciente"
export { Orientacoes } from "./pacientePages/orientacoes"
export { ConceitosImportantes } from "./pacientePages/conceitosImportantes"
export { LinksUteis } from "./pacientePages/linksUteis"
export { Faq } from "./pacientePages/faq"